project_name: lsif-go

dist: release

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
-
  main: ./cmd/lsif-go/
  binary: lsif-go
  ldflags:
    - -X main.buildTag={{.Version}}
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64

archives:
- id: tarball
  format: tar.gz
- id: bin
  format: binary
  wrap_in_directory: false
  name_template: "src_{{ .Os }}_{{ .Arch }}"

dockers:
  - binaries:
    - lsif-go
    image_templates:
    - "sourcegraph/lsif-go:{{ .Tag }}"
    - "sourcegraph/lsif-go:{{ .Major }}"
    - "sourcegraph/lsif-go:{{ .Major }}.{{ .Minor }}"
    - "sourcegraph/lsif-go:latest"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
