#!/usr/bin/env bash

set -eu
pushd "$(dirname "${BASH_SOURCE[0]}")"/../..

# Skip the rest if this is pipeline upload or empty
if [[ "${BUILDKITE_COMMAND:-}" =~ "buildkite-agent pipeline upload".* ]]; then
  exit 0
fi

echo "Installing asdf dependencies"
asdf install
