name: release

on:
  push:
    branches:
      - garo/fix-ci

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.131.1
          args: release --rm-dist --skip-publish --snapshot
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
